export type ApiError = { code: string; message: string; retryable: boolean };
export type TicketStatus = "OPEN" | "IN_PROGRESS" | "RESOLVED";
export type Context = Partial<Record<"customerId" | "orderId" | "productId" | "requestId" | "checkoutKey" | "occurredAt", string | null>>;
export type Ticket = { ticketId: string; version: number; title: string; message: string; context: Context;
  assigneeId: string | null; status: TicketStatus; createdAt: string; updatedAt: string };
export type Assignee = { id: string; displayName: string };
export type AnalysisSummary = { analysisRequestId: string; ticketVersion: number; submissionStatus: "PENDING" | "SUBMITTED" | "FAILED";
  investigationId: string | null; investigationStatus: InvestigationStatus | null; createdAt: string; updatedAt: string };
export type TicketDetail = { ticket: Ticket; analyses: AnalysisSummary[] };
export type InvestigationStatus = "QUEUED" | "RUNNING" | "COMPLETED" | "NEEDS_INPUT" | "FAILED";
export type InvestigationInput = { schemaVersion: string; ticketId: string; ticketVersion: number; requestKey: string;
  message: string; context: Context; previousInvestigationId: string | null };
export type Evidence = { evidenceId: string; type: "DATA" | "LOG" | "CODE" | "POLICY"; summary: string;
  observedAt: string; source: Record<string, unknown> };
export type EvidenceDetail = Evidence & { content: unknown; truncated: boolean };
export type ReportItem = { id: string; description: string; evidenceIds: string[] };
export type AnalysisReport = { schemaVersion: string; summary: string; facts: ReportItem[];
  hypotheses: (ReportItem & { supportLevel: "SUPPORTED" | "PARTIAL" | "UNVERIFIED"; limitations: string[] })[];
  actions: (ReportItem & { requiresHumanAction: true })[];
  prevention: (ReportItem & { targetPaths: string[]; validationSteps: string[] })[];
  missingInformation: { field: string; reason: string }[] };
export type ToolExecution = { toolExecutionId: string; toolName: string; status: string; startedAt: string;
  finishedAt: string | null; summary: string; evidenceIds: string[]; error: ApiError | null };
export type Investigation = { schemaVersion: string; investigationId: string; ticketId: string; ticketVersion: number;
  status: InvestigationStatus; createdAt: string; updatedAt: string; progress: ToolExecution[];
  evidence: Evidence[]; report: AnalysisReport | null; error: ApiError | null };
export type AnalysisView = { analysisRequestId: string; ticketId: string; ticketVersion: number;
  submissionStatus: "PENDING" | "SUBMITTED" | "FAILED"; investigationId: string | null;
  input: InvestigationInput; investigation: Investigation | null; submissionError: ApiError | null;
  syncError: ApiError | null; lastSyncedAt: string | null; createdAt: string; updatedAt: string };
export type AnalysisRequest = { requestKey: string; ticketVersion: number; previousInvestigationId: string | null };
